using System;
using System.Globalization;
using System.Resources;
using TeknoParrotUi.Properties;

namespace TeknoParrotUi.Helpers
{
    public static class ResourceProvider
    {
        private static readonly ResourceManager ResourceManager = Resources.ResourceManager;
        private static readonly CultureInfo Culture = CultureInfo.CurrentUICulture;

        // Existing properties
        public static string SettingsSaveSettings => ResourceManager.GetString("SettingsSaveSettings", Culture);
        public static string Back => ResourceManager.GetString("Back", Culture);

        // All resources from the provided file
        public static string AboutCredits => ResourceManager.GetString("AboutCredits", Culture);
        public static string AddGame => ResourceManager.GetString("AddGame", Culture);
        public static string Cancel => ResourceManager.GetString("Cancel", Culture);
        public static string DeleteGame => ResourceManager.GetString("DeleteGame", Culture);
        public static string DownloaderCancelled => ResourceManager.GetString("DownloaderCancelled", Culture);
        public static string DownloaderComplete => ResourceManager.GetString("DownloaderComplete", Culture);
        public static string DownloaderDownloading => ResourceManager.GetString("DownloaderDownloading", Culture);
        public static string DownloaderError => ResourceManager.GetString("DownloaderError", Culture);
        public static string Error => ResourceManager.GetString("Error", Culture);
        public static string ErrorAllowedRange => ResourceManager.GetString("ErrorAllowedRange", Culture);
        public static string ErrorAlreadyRunning => ResourceManager.GetString("ErrorAlreadyRunning", Culture);
        public static string ErrorCannotParseGUID => ResourceManager.GetString("ErrorCannotParseGUID", Culture);
        public static string ErrorCantLoadParrotData => ResourceManager.GetString("ErrorCantLoadParrotData", Culture);
        public static string ErrorCantLoadProfile => ResourceManager.GetString("ErrorCantLoadProfile", Culture);
        public static string ErrorCantSaveParrotData => ResourceManager.GetString("ErrorCantSaveParrotData", Culture);
        public static string ErrorGamePathNotSet => ResourceManager.GetString("ErrorGamePathNotSet", Culture);
        public static string ErrorMasterServerOffline => ResourceManager.GetString("ErrorMasterServerOffline", Culture);
        public static string ErrorNoAPM3Id => ResourceManager.GetString("ErrorNoAPM3Id", Culture);
        public static string ErrorNoOnlineId => ResourceManager.GetString("ErrorNoOnlineId", Culture);
        public static string ErrorOldTeknoParrotDirectory => ResourceManager.GetString("ErrorOldTeknoParrotDirectory", Culture);
        public static string FirstRun => ResourceManager.GetString("FirstRun", Culture);
        public static string GameList => ResourceManager.GetString("GameList", Culture);
        public static string GameRunning => ResourceManager.GetString("GameRunning", Culture);
        public static string GameRunningCheckTaskMgr => ResourceManager.GetString("GameRunningCheckTaskMgr", Culture);
        public static string GameRunningForceQuit => ResourceManager.GetString("GameRunningForceQuit", Culture);
        public static string GameRunningGameStopped => ResourceManager.GetString("GameRunningGameStopped", Culture);
        public static string GameSettingsGameExecutable => ResourceManager.GetString("GameSettingsGameExecutable", Culture);
        public static string GameSettingsGameExecutableFilter => ResourceManager.GetString("GameSettingsGameExecutableFilter", Culture);
        public static string GameSettingsSelectGameExecutable => ResourceManager.GetString("GameSettingsSelectGameExecutable", Culture);
        public static string Information => ResourceManager.GetString("Information", Culture);
        public static string Library64bit => ResourceManager.GetString("Library64bit", Culture);
        public static string LibraryAnotherEmulator => ResourceManager.GetString("LibraryAnotherEmulator", Culture);
        public static string LibraryBadiDMAC => ResourceManager.GetString("LibraryBadiDMAC", Culture);
        public static string LibraryCantFindGame => ResourceManager.GetString("LibraryCantFindGame", Culture);
        public static string LibraryCantFindLoader => ResourceManager.GetString("LibraryCantFindLoader", Culture);
        public static string LibraryControllerSetup => ResourceManager.GetString("LibraryControllerSetup", Culture);
        public static string LibraryDeleteGame => ResourceManager.GetString("LibraryDeleteGame", Culture);
        public static string LibraryDownloadAllIcons => ResourceManager.GetString("LibraryDownloadAllIcons", Culture);
        public static string LibraryDownloadMissingIcons => ResourceManager.GetString("LibraryDownloadMissingIcons", Culture);
        public static string LibraryEmulator => ResourceManager.GetString("LibraryEmulator", Culture);
        public static string LibraryGameLocation2NotSet => ResourceManager.GetString("LibraryGameLocation2NotSet", Culture);
        public static string LibraryGameLocationNotSet => ResourceManager.GetString("LibraryGameLocationNotSet", Culture);
        public static string LibraryGameSettings => ResourceManager.GetString("LibraryGameSettings", Culture);
        public static string LibraryInvalidFiles => ResourceManager.GetString("LibraryInvalidFiles", Culture);
        public static string LibraryInvalidFilesContinue => ResourceManager.GetString("LibraryInvalidFilesContinue", Culture);
        public static string LibraryLaunchGame => ResourceManager.GetString("LibraryLaunchGame", Culture);
        public static string LibraryMoreInfo => ResourceManager.GetString("LibraryMoreInfo", Culture);
        public static string LibraryNeedsAdmin => ResourceManager.GetString("LibraryNeedsAdmin", Culture);
        public static string LibraryNoGames => ResourceManager.GetString("LibraryNoGames", Culture);
        public static string LibraryNoHashes => ResourceManager.GetString("LibraryNoHashes", Culture);
        public static string LibraryNoInfo => ResourceManager.GetString("LibraryNoInfo", Culture);
        public static string LibraryOnlineProfile => ResourceManager.GetString("LibraryOnlineProfile", Culture);
        public static string LibraryPlayOnline => ResourceManager.GetString("LibraryPlayOnline", Culture);
        public static string LibraryTestMenu => ResourceManager.GetString("LibraryTestMenu", Culture);
        public static string LibraryToggleTestMode => ResourceManager.GetString("LibraryToggleTestMode", Culture);
        public static string LibraryVerifyGame => ResourceManager.GetString("LibraryVerifyGame", Culture);
        public static string MainAbout => ResourceManager.GetString("MainAbout", Culture);
        public static string MainAreYouSure => ResourceManager.GetString("MainAreYouSure", Culture);
        public static string MainCheckUpdates => ResourceManager.GetString("MainCheckUpdates", Culture);
        public static string MainDownloadMissingIcons => ResourceManager.GetString("MainDownloadMissingIcons", Culture);
        public static string MainLibrary => ResourceManager.GetString("MainLibrary", Culture);
        public static string MainQuit => ResourceManager.GetString("MainQuit", Culture);
        public static string MainRomScanner => ResourceManager.GetString("MainRomScanner", Culture);
        public static string MainSettings => ResourceManager.GetString("MainSettings", Culture);
        public static string MainTPOnline => ResourceManager.GetString("MainTPOnline", Culture);
        public static string MainTPOnlineNew => ResourceManager.GetString("MainTPOnlineNew", Culture);
        public static string No => ResourceManager.GetString("No", Culture);
        public static string PatreonBecomeAPatron => ResourceManager.GetString("PatreonBecomeAPatron", Culture);
        public static string PatreonDeregisterKey => ResourceManager.GetString("PatreonDeregisterKey", Culture);
        public static string PatreonError => ResourceManager.GetString("PatreonError", Culture);
        public static string PatreonMissingBudgie => ResourceManager.GetString("PatreonMissingBudgie", Culture);
        public static string PatreonMustNotBeBlank => ResourceManager.GetString("PatreonMustNotBeBlank", Culture);
        public static string PatreonRegisterKey => ResourceManager.GetString("PatreonRegisterKey", Culture);
        public static string PatreonStatus => ResourceManager.GetString("PatreonStatus", Culture);
        public static string SettingsCheckForUpdates => ResourceManager.GetString("SettingsCheckForUpdates", Culture);
        public static string SettingsCommon => ResourceManager.GetString("SettingsCommon", Culture);
        public static string SettingsConfirmExit => ResourceManager.GetString("SettingsConfirmExit", Culture);
        public static string SettingsDInputWheel => ResourceManager.GetString("SettingsDInputWheel", Culture);
        public static string SettingsDownloadFFB => ResourceManager.GetString("SettingsDownloadFFB", Culture);
        public static string SettingsDownloadIcon => ResourceManager.GetString("SettingsDownloadIcon", Culture);
        public static string SettingsElf2LogToFile => ResourceManager.GetString("SettingsElf2LogToFile", Culture);
        public static string SettingsElfldr2 => ResourceManager.GetString("SettingsElfldr2", Culture);
        public static string SettingsElfldr2NetworkAdapter => ResourceManager.GetString("SettingsElfldr2NetworkAdapter", Culture);
        public static string SettingsFullBrake => ResourceManager.GetString("SettingsFullBrake", Culture);
        public static string SettingsFullGas => ResourceManager.GetString("SettingsFullGas", Culture);
        public static string SettingsHardwareAccel => ResourceManager.GetString("SettingsHardwareAccel", Culture);
        public static string SettingsHideConsoleWindows => ResourceManager.GetString("SettingsHideConsoleWindows", Culture);
        public static string SettingsHideVanguardWarning => ResourceManager.GetString("SettingsHideVanguardWarning", Culture);
        public static string SettingsJoystickGunSettings => ResourceManager.GetString("SettingsJoystickGunSettings", Culture);
        public static string SettingsLoadLastPlayed => ResourceManager.GetString("SettingsLoadLastPlayed", Culture);
        public static string SettingsP1GunJoystickSensitivity => ResourceManager.GetString("SettingsP1GunJoystickSensitivity", Culture);
        public static string SettingsP2GunJoystickSensitivity => ResourceManager.GetString("SettingsP2GunJoystickSensitivity", Culture);
        public static string SettingsReverseBrake => ResourceManager.GetString("SettingsReverseBrake", Culture);
        public static string SettingsReverseGas => ResourceManager.GetString("SettingsReverseGas", Culture);
        public static string SettingsShowGameOnDiscord => ResourceManager.GetString("SettingsShowGameOnDiscord", Culture);
        public static string SettingsSto0zZone => ResourceManager.GetString("SettingsSto0zZone", Culture);
        public static string SettingsSto0zZoneTitle => ResourceManager.GetString("SettingsSto0zZoneTitle", Culture);
        public static string SettingsUIColour => ResourceManager.GetString("SettingsUIColour", Culture);
        public static string SettingsUICustomization => ResourceManager.GetString("SettingsUICustomization", Culture);
        public static string SettingsUIDarkMode => ResourceManager.GetString("SettingsUIDarkMode", Culture);
        public static string SettingsUIHolidayThemes => ResourceManager.GetString("SettingsUIHolidayThemes", Culture);
        public static string SuccessfullySaved => ResourceManager.GetString("SuccessfullySaved", Culture);
        public static string TPOCreateLobby => ResourceManager.GetString("TPOCreateLobby", Culture);
        public static string TPOFilter => ResourceManager.GetString("TPOFilter", Culture);
        public static string TPOGame => ResourceManager.GetString("TPOGame", Culture);
        public static string TPOJoinLobby => ResourceManager.GetString("TPOJoinLobby", Culture);
        public static string TPOLobbyName => ResourceManager.GetString("TPOLobbyName", Culture);
        public static string TPOPlayers => ResourceManager.GetString("TPOPlayers", Culture);
        public static string TPORefresh => ResourceManager.GetString("TPORefresh", Culture);
        public static string UpdaterAvailable => ResourceManager.GetString("UpdaterAvailable", Culture);
        public static string UpdaterNotInstalled => ResourceManager.GetString("UpdaterNotInstalled", Culture);
        public static string UpdaterOpenChangelog => ResourceManager.GetString("UpdaterOpenChangelog", Culture);
        public static string UpdaterRestart => ResourceManager.GetString("UpdaterRestart", Culture);
        public static string UpdaterSuccess => ResourceManager.GetString("UpdaterSuccess", Culture);
        public static string UpdaterUpdate => ResourceManager.GetString("UpdaterUpdate", Culture);
        public static string VanguardDetected => ResourceManager.GetString("VanguardDetected", Culture);
        public static string VerifyCancelled => ResourceManager.GetString("VerifyCancelled", Culture);
        public static string VerifyChecking => ResourceManager.GetString("VerifyChecking", Culture);
        public static string VerifyFilesInvalid => ResourceManager.GetString("VerifyFilesInvalid", Culture);
        public static string VerifyFilesInvalidExplain => ResourceManager.GetString("VerifyFilesInvalidExplain", Culture);
        public static string VerifyFilesValid => ResourceManager.GetString("VerifyFilesValid", Culture);
        public static string VerifyInvalid => ResourceManager.GetString("VerifyInvalid", Culture);
        public static string VerifyValid => ResourceManager.GetString("VerifyValid", Culture);
        public static string Warning => ResourceManager.GetString("Warning", Culture);
        public static string Yes => ResourceManager.GetString("Yes", Culture);
    }
}