//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoParrotUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeknoParrotUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Reaver, NTAuthority, avail and the community.
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Game.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Cancelled.
        /// </summary>
        public static string DownloaderCancelled {
            get {
                return ResourceManager.GetString("DownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        public static string DownloaderComplete {
            get {
                return ResourceManager.GetString("DownloaderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DownloaderDownloading {
            get {
                return ResourceManager.GetString("DownloaderDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Downloading.
        /// </summary>
        public static string DownloaderError {
            get {
                return ResourceManager.GetString("DownloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknoParrotUI seems to already be running, want to close it?.
        /// </summary>
        public static string ErrorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location not set! Please set it in Game Settings..
        /// </summary>
        public static string ErrorGamePathNotSet {
            get {
                return ResourceManager.GetString("ErrorGamePathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems you have extracted me to the directory of old TeknoParrot. Please extract me to a new directory instead!.
        /// </summary>
        public static string ErrorOldTeknoParrotDirectory {
            get {
                return ResourceManager.GetString("ErrorOldTeknoParrotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games:.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is 64-bit and cannot run on a 32-bit OS..
        /// </summary>
        public static string Library64bit {
            get {
                return ResourceManager.GetString("Library64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you have other emulator already in use.\nPlease remove the following files from the game directory:\n.
        /// </summary>
        public static string LibraryAnotherEmulator {
            get {
                return ResourceManager.GetString("LibraryAnotherEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update OpenParrot!\nYou seem to be using an unofficial {0} file! The game may crash or be unstable. Continue?.
        /// </summary>
        public static string LibraryBadiDMAC {
            get {
                return ResourceManager.GetString("LibraryBadiDMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find game exe at: {0}.
        /// </summary>
        public static string LibraryCantFindGame {
            get {
                return ResourceManager.GetString("LibraryCantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0}!\nPlease re-extract TeknoParrot..
        /// </summary>
        public static string LibraryCantFindLoader {
            get {
                return ResourceManager.GetString("LibraryCantFindLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLER SETUP.
        /// </summary>
        public static string LibraryControllerSetup {
            get {
                return ResourceManager.GetString("LibraryControllerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will download every missing icon for TeknoParrot. The file is around 50 megabytes. Are you sure you want to continue?.
        /// </summary>
        public static string LibraryDownloadAllIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadAllIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD MISSING ICONS.
        /// </summary>
        public static string LibraryDownloadMissingIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        public static string LibraryEmulator {
            get {
                return ResourceManager.GetString("LibraryEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location not set! Please set it in Game Settings..
        /// </summary>
        public static string LibraryGameLocationNotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME SETTINGS.
        /// </summary>
        public static string LibraryGameSettings {
            get {
                return ResourceManager.GetString("LibraryGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are possibly some invalid files in your game directory.\nThe following files may need to be removed from the game directory, unless you know what they are:\n.
        /// </summary>
        public static string LibraryInvalidFiles {
            get {
                return ResourceManager.GetString("LibraryInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Yes to continue running the game as is..
        /// </summary>
        public static string LibraryInvalidFilesContinue {
            get {
                return ResourceManager.GetString("LibraryInvalidFilesContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH GAME.
        /// </summary>
        public static string LibraryLaunchGame {
            get {
                return ResourceManager.GetString("LibraryLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE INFO.
        /// </summary>
        public static string LibraryMoreInfo {
            get {
                return ResourceManager.GetString("LibraryMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you are not running TeknoParrotUI as Administrator! The game {0} requires the UI to be running as Administrator to function properly. Continue?.
        /// </summary>
        public static string LibraryNeedsAdmin {
            get {
                return ResourceManager.GetString("LibraryNeedsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no games set up. Do you want to add one now?.
        /// </summary>
        public static string LibraryNoGames {
            get {
                return ResourceManager.GetString("LibraryNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you are trying to verify a game that doesn&apos;t have a clean file hash list yet..
        /// </summary>
        public static string LibraryNoHashes {
            get {
                return ResourceManager.GetString("LibraryNoHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Game Information Available.
        /// </summary>
        public static string LibraryNoInfo {
            get {
                return ResourceManager.GetString("LibraryNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Menu.
        /// </summary>
        public static string LibraryTestMenu {
            get {
                return ResourceManager.GetString("LibraryTestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle test mode..
        /// </summary>
        public static string LibraryToggleTestMode {
            get {
                return ResourceManager.GetString("LibraryToggleTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY GAME.
        /// </summary>
        public static string LibraryVerifyGame {
            get {
                return ResourceManager.GetString("LibraryVerifyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainAbout {
            get {
                return ResourceManager.GetString("MainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MainAreYouSure {
            get {
                return ResourceManager.GetString("MainAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MainLibrary {
            get {
                return ResourceManager.GetString("MainLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainQuit {
            get {
                return ResourceManager.GetString("MainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknoParrot Online.
        /// </summary>
        public static string MainTPOnline {
            get {
                return ResourceManager.GetString("MainTPOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available..
        /// </summary>
        public static string UpdaterAvailable {
            get {
                return ResourceManager.GetString("UpdaterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UpdaterCancel {
            get {
                return ResourceManager.GetString("UpdaterCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string UpdaterNotInstalled {
            get {
                return ResourceManager.GetString("UpdaterNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Changelog.
        /// </summary>
        public static string UpdaterOpenChangelog {
            get {
                return ResourceManager.GetString("UpdaterOpenChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like TeknoParrotUi to restart to finish the update? Otherwise, TeknoParrotUi will close..
        /// </summary>
        public static string UpdaterRestart {
            get {
                return ResourceManager.GetString("UpdaterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully updated {0} to {1}.
        /// </summary>
        public static string UpdaterSuccess {
            get {
                return ResourceManager.GetString("UpdaterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdaterUpdate {
            get {
                return ResourceManager.GetString("UpdaterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
