//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoParrotUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeknoParrotUi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Reaver, NTAuthority, avail and the community.
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Game.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Game.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Cancelled.
        /// </summary>
        public static string DownloaderCancelled {
            get {
                return ResourceManager.GetString("DownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        public static string DownloaderComplete {
            get {
                return ResourceManager.GetString("DownloaderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DownloaderDownloading {
            get {
                return ResourceManager.GetString("DownloaderDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Downloading.
        /// </summary>
        public static string DownloaderError {
            get {
                return ResourceManager.GetString("DownloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed range is 0-8191!.
        /// </summary>
        public static string ErrorAllowedRange {
            get {
                return ResourceManager.GetString("ErrorAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknoParrotUI seems to already be running, want to close it?.
        /// </summary>
        public static string ErrorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse GUID: {0}. Please check that data has the GUID value only and nothing else!.
        /// </summary>
        public static string ErrorCannotParseGUID {
            get {
                return ResourceManager.GetString("ErrorCannotParseGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened during loading ParrotData.xml! Generate new one by saving!
        ///
        ///{0}.
        /// </summary>
        public static string ErrorCantLoadParrotData {
            get {
                return ResourceManager.GetString("ErrorCantLoadParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading {0}, Would you to delete it?.
        /// </summary>
        public static string ErrorCantLoadProfile {
            get {
                return ResourceManager.GetString("ErrorCantLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception happened during ParrotData.xml saving!
        ///
        ///{0}.
        /// </summary>
        public static string ErrorCantSaveParrotData {
            get {
                return ResourceManager.GetString("ErrorCantSaveParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location not set! Please set it in Game Settings..
        /// </summary>
        public static string ErrorGamePathNotSet {
            get {
                return ResourceManager.GetString("ErrorGamePathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master server is offline..
        /// </summary>
        public static string ErrorMasterServerOffline {
            get {
                return ResourceManager.GetString("ErrorMasterServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (or invalid) APM3Id set in profile. APM3 games need these to work. Please click on the online Profile button to get yours and type it into the APM3Id field in the game settings..
        /// </summary>
        public static string ErrorNoAPM3Id {
            get {
                return ResourceManager.GetString("ErrorNoAPM3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems you have extracted me to the directory of old TeknoParrot. Please extract me to a new directory instead!.
        /// </summary>
        public static string ErrorOldTeknoParrotDirectory {
            get {
                return ResourceManager.GetString("ErrorOldTeknoParrotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like this is first time you are running TeknoParrotUi, please set emulation settings..
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games:.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Running.
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you force closed the emulator, you should check Task Manager for any processes still running that are related to the emulator or your game..
        /// </summary>
        public static string GameRunningCheckTaskMgr {
            get {
                return ResourceManager.GetString("GameRunningCheckTaskMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Quit Game.
        /// </summary>
        public static string GameRunningForceQuit {
            get {
                return ResourceManager.GetString("GameRunningForceQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Stopped.
        /// </summary>
        public static string GameRunningGameStopped {
            get {
                return ResourceManager.GetString("GameRunningGameStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Executable:.
        /// </summary>
        public static string GameSettingsGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game executable.
        /// </summary>
        public static string GameSettingsGameExecutableFilter {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select game executable.
        /// </summary>
        public static string GameSettingsSelectGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsSelectGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is 64-bit and cannot run on a 32-bit OS..
        /// </summary>
        public static string Library64bit {
            get {
                return ResourceManager.GetString("Library64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you have other emulator already in use.
        ///Please remove the following files from the game directory:
        ///  .
        /// </summary>
        public static string LibraryAnotherEmulator {
            get {
                return ResourceManager.GetString("LibraryAnotherEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update OpenParrot!
        ///You seem to be using an unofficial {0} file! The game may crash or be unstable. Continue?.
        /// </summary>
        public static string LibraryBadiDMAC {
            get {
                return ResourceManager.GetString("LibraryBadiDMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find game exe at: {0}.
        /// </summary>
        public static string LibraryCantFindGame {
            get {
                return ResourceManager.GetString("LibraryCantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find {0}!
        ///It is probably removed by your anti-virus software.
        ///Please re-extract TeknoParrot..
        /// </summary>
        public static string LibraryCantFindLoader {
            get {
                return ResourceManager.GetString("LibraryCantFindLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROLLER SETUP.
        /// </summary>
        public static string LibraryControllerSetup {
            get {
                return ResourceManager.GetString("LibraryControllerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will download every missing icon for TeknoParrot. The file is around 50 megabytes. Are you sure you want to continue?.
        /// </summary>
        public static string LibraryDownloadAllIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadAllIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD MISSING ICONS.
        /// </summary>
        public static string LibraryDownloadMissingIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator.
        /// </summary>
        public static string LibraryEmulator {
            get {
                return ResourceManager.GetString("LibraryEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second game location not set! Please set it in Game Settings..
        /// </summary>
        public static string LibraryGameLocation2NotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocation2NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location not set! Please set it in Game Settings..
        /// </summary>
        public static string LibraryGameLocationNotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME SETTINGS.
        /// </summary>
        public static string LibraryGameSettings {
            get {
                return ResourceManager.GetString("LibraryGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are possibly some invalid files in your game directory.
        ///The following files may need to be removed from the game directory, unless you know what they are:
        ///  .
        /// </summary>
        public static string LibraryInvalidFiles {
            get {
                return ResourceManager.GetString("LibraryInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Yes to continue running the game as is..
        /// </summary>
        public static string LibraryInvalidFilesContinue {
            get {
                return ResourceManager.GetString("LibraryInvalidFilesContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAUNCH GAME.
        /// </summary>
        public static string LibraryLaunchGame {
            get {
                return ResourceManager.GetString("LibraryLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN WIKI.
        /// </summary>
        public static string LibraryMoreInfo {
            get {
                return ResourceManager.GetString("LibraryMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like you are not running TeknoParrotUI as Administrator! The game {0} requires the UI to be running as Administrator to function properly. Continue anyway WITHOUT admin rights? This might cause issues or crashes..
        /// </summary>
        public static string LibraryNeedsAdmin {
            get {
                return ResourceManager.GetString("LibraryNeedsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no games set up. Do you want to add one now?.
        /// </summary>
        public static string LibraryNoGames {
            get {
                return ResourceManager.GetString("LibraryNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you are trying to verify a game that doesn&apos;t have a clean file hash list yet..
        /// </summary>
        public static string LibraryNoHashes {
            get {
                return ResourceManager.GetString("LibraryNoHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Game Information Available.
        /// </summary>
        public static string LibraryNoInfo {
            get {
                return ResourceManager.GetString("LibraryNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE PROFILE.
        /// </summary>
        public static string LibraryOnlineProfile {
            get {
                return ResourceManager.GetString("LibraryOnlineProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Menu.
        /// </summary>
        public static string LibraryTestMenu {
            get {
                return ResourceManager.GetString("LibraryTestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle test mode..
        /// </summary>
        public static string LibraryToggleTestMode {
            get {
                return ResourceManager.GetString("LibraryToggleTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFY GAME.
        /// </summary>
        public static string LibraryVerifyGame {
            get {
                return ResourceManager.GetString("LibraryVerifyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainAbout {
            get {
                return ResourceManager.GetString("MainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MainAreYouSure {
            get {
                return ResourceManager.GetString("MainAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MainCheckUpdates {
            get {
                return ResourceManager.GetString("MainCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Icons.
        /// </summary>
        public static string MainDownloadMissingIcons {
            get {
                return ResourceManager.GetString("MainDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string MainLibrary {
            get {
                return ResourceManager.GetString("MainLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string MainQuit {
            get {
                return ResourceManager.GetString("MainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Online (OLD).
        /// </summary>
        public static string MainTPOnline {
            get {
                return ResourceManager.GetString("MainTPOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Online (NEW).
        /// </summary>
        public static string MainTPOnlineNew {
            get {
                return ResourceManager.GetString("MainTPOnlineNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become A Patron!.
        /// </summary>
        public static string PatreonBecomeAPatron {
            get {
                return ResourceManager.GetString("PatreonBecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeRegister Patreon Key.
        /// </summary>
        public static string PatreonDeregisterKey {
            get {
                return ResourceManager.GetString("PatreonDeregisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from other process:.
        /// </summary>
        public static string PatreonError {
            get {
                return ResourceManager.GetString("PatreonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patreon Key must not be blank.
        /// </summary>
        public static string PatreonMustNotBeBlank {
            get {
                return ResourceManager.GetString("PatreonMustNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Patreon Key.
        /// </summary>
        public static string PatreonRegisterKey {
            get {
                return ResourceManager.GetString("PatreonRegisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string PatreonStatus {
            get {
                return ResourceManager.GetString("PatreonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on launch.
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string SettingsCommon {
            get {
                return ResourceManager.GetString("SettingsCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation prompt on exit.
        /// </summary>
        public static string SettingsConfirmExit {
            get {
                return ResourceManager.GetString("SettingsConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Input Wheel Settings.
        /// </summary>
        public static string SettingsDInputWheel {
            get {
                return ResourceManager.GetString("SettingsDInputWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Force Feedback Plugin.
        /// </summary>
        public static string SettingsDownloadFFB {
            get {
                return ResourceManager.GetString("SettingsDownloadFFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download game icon when selected.
        /// </summary>
        public static string SettingsDownloadIcon {
            get {
                return ResourceManager.GetString("SettingsDownloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Axis Brake.
        /// </summary>
        public static string SettingsFullBrake {
            get {
                return ResourceManager.GetString("SettingsFullBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Axis Gas.
        /// </summary>
        public static string SettingsFullGas {
            get {
                return ResourceManager.GetString("SettingsFullGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Hardware Acceleration in UI.
        /// </summary>
        public static string SettingsHardwareAccel {
            get {
                return ResourceManager.GetString("SettingsHardwareAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide console windows.
        /// </summary>
        public static string SettingsHideConsoleWindows {
            get {
                return ResourceManager.GetString("SettingsHideConsoleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Vanguard Warning.
        /// </summary>
        public static string SettingsHideVanguardWarning {
            get {
                return ResourceManager.GetString("SettingsHideVanguardWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick Gun Settings.
        /// </summary>
        public static string SettingsJoystickGunSettings {
            get {
                return ResourceManager.GetString("SettingsJoystickGunSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load last game played on launch.
        /// </summary>
        public static string SettingsLoadLastPlayed {
            get {
                return ResourceManager.GetString("SettingsLoadLastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1 Gun Joystick Sensitivity.
        /// </summary>
        public static string SettingsP1GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP1GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2 Gun Joystick Sensitivity.
        /// </summary>
        public static string SettingsP2GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP2GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Axis Brake.
        /// </summary>
        public static string SettingsReverseBrake {
            get {
                return ResourceManager.GetString("SettingsReverseBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Axis Gas.
        /// </summary>
        public static string SettingsReverseGas {
            get {
                return ResourceManager.GetString("SettingsReverseGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        public static string SettingsSaveSettings {
            get {
                return ResourceManager.GetString("SettingsSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current game playing on Discord.
        /// </summary>
        public static string SettingsShowGameOnDiscord {
            get {
                return ResourceManager.GetString("SettingsShowGameOnDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sTo0z Zone.
        /// </summary>
        public static string SettingsSto0zZone {
            get {
                return ResourceManager.GetString("SettingsSto0zZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sto0z Zone.
        /// </summary>
        public static string SettingsSto0zZoneTitle {
            get {
                return ResourceManager.GetString("SettingsSto0zZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title colour.
        /// </summary>
        public static string SettingsUIColour {
            get {
                return ResourceManager.GetString("SettingsUIColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Customization (Patreon).
        /// </summary>
        public static string SettingsUICustomization {
            get {
                return ResourceManager.GetString("SettingsUICustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string SettingsUIDarkMode {
            get {
                return ResourceManager.GetString("SettingsUIDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a different theme on holidays.
        /// </summary>
        public static string SettingsUIHolidayThemes {
            get {
                return ResourceManager.GetString("SettingsUIHolidayThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved {0}!.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Lobby and Launch Game.
        /// </summary>
        public static string TPOCreateLobby {
            get {
                return ResourceManager.GetString("TPOCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by game:.
        /// </summary>
        public static string TPOFilter {
            get {
                return ResourceManager.GetString("TPOFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string TPOGame {
            get {
                return ResourceManager.GetString("TPOGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lobby and Launch Game.
        /// </summary>
        public static string TPOJoinLobby {
            get {
                return ResourceManager.GetString("TPOJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby Name.
        /// </summary>
        public static string TPOLobbyName {
            get {
                return ResourceManager.GetString("TPOLobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string TPOPlayers {
            get {
                return ResourceManager.GetString("TPOPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Lobbies.
        /// </summary>
        public static string TPORefresh {
            get {
                return ResourceManager.GetString("TPORefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new update available..
        /// </summary>
        public static string UpdaterAvailable {
            get {
                return ResourceManager.GetString("UpdaterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string UpdaterNotInstalled {
            get {
                return ResourceManager.GetString("UpdaterNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Changelog.
        /// </summary>
        public static string UpdaterOpenChangelog {
            get {
                return ResourceManager.GetString("UpdaterOpenChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like TeknoParrotUi to restart to finish the update? Otherwise, TeknoParrotUi will close..
        /// </summary>
        public static string UpdaterRestart {
            get {
                return ResourceManager.GetString("UpdaterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully updated {0} to {1}.
        /// </summary>
        public static string UpdaterSuccess {
            get {
                return ResourceManager.GetString("UpdaterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdaterUpdate {
            get {
                return ResourceManager.GetString("UpdaterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknoParrot has detected that you have the anti-cheat system for VALORANT currently running, Riot Vanguard. Vanguard interferes with how TeknoParrot loads games and is known to cause issues! 
        ///
        ///It is highly recommended that you right click on the Vanguard icon in your system tray (next to the clock), and click &quot;Exit Vanguard&quot;. This will mean you cannot play VALORANT until you restart your computer, but TeknoParrot games should now launch properly.
        ///
        ///Click &quot;OK&quot; to continue loading TeknoParrot..
        /// </summary>
        public static string VanguardDetected {
            get {
                return ResourceManager.GetString("VanguardDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Cancelled..
        /// </summary>
        public static string VerifyCancelled {
            get {
                return ResourceManager.GetString("VerifyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Game Integrity....
        /// </summary>
        public static string VerifyChecking {
            get {
                return ResourceManager.GetString("VerifyChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files invalid.
        /// </summary>
        public static string VerifyFilesInvalid {
            get {
                return ResourceManager.GetString("VerifyFilesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game appears to have invalid files. This could be due to a bad download, bad dump, virus infection, or you have modifications installed like resolution and english patches..
        /// </summary>
        public static string VerifyFilesInvalidExplain {
            get {
                return ResourceManager.GetString("VerifyFilesInvalidExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files valid.
        /// </summary>
        public static string VerifyFilesValid {
            get {
                return ResourceManager.GetString("VerifyFilesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid:.
        /// </summary>
        public static string VerifyInvalid {
            get {
                return ResourceManager.GetString("VerifyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid:.
        /// </summary>
        public static string VerifyValid {
            get {
                return ResourceManager.GetString("VerifyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
