//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknoParrotUi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fi_FI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fi_FI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeknoParrotUi.Properties.Resources-fi-FI", typeof(Resources_fi_FI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekijät Reaver, NTAuthority, avail sekä yhteisö.
        /// </summary>
        public static string AboutCredits {
            get {
                return ResourceManager.GetString("AboutCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisää Peli.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takaisin.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peruuta.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista Peli.
        /// </summary>
        public static string DeleteGame {
            get {
                return ResourceManager.GetString("DeleteGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataus Peruttu.
        /// </summary>
        public static string DownloaderCancelled {
            get {
                return ResourceManager.GetString("DownloaderCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataus Valmis.
        /// </summary>
        public static string DownloaderComplete {
            get {
                return ResourceManager.GetString("DownloaderComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladataan.
        /// </summary>
        public static string DownloaderDownloading {
            get {
                return ResourceManager.GetString("DownloaderDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataus Virhe.
        /// </summary>
        public static string DownloaderError {
            get {
                return ResourceManager.GetString("DownloaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sallittu arvon väli on 0-8191!.
        /// </summary>
        public static string ErrorAllowedRange {
            get {
                return ResourceManager.GetString("ErrorAllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknoParrotUI näyttää olevan jo käynnissä, haluatko sulkea sen?.
        /// </summary>
        public static string ErrorAlreadyRunning {
            get {
                return ResourceManager.GetString("ErrorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En voi parsia GUID arvoa: {0}. Tarkista että data on vain numeroita..
        /// </summary>
        public static string ErrorCannotParseGUID {
            get {
                return ResourceManager.GetString("ErrorCannotParseGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe ladattaessa ParrotData.xml tiedostoa! Tee uusi tallentamalla asetukset. {0}.
        /// </summary>
        public static string ErrorCantLoadParrotData {
            get {
                return ResourceManager.GetString("ErrorCantLoadParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe ladattaessa {0}, poistetaanko tiedosto?.
        /// </summary>
        public static string ErrorCantLoadProfile {
            get {
                return ResourceManager.GetString("ErrorCantLoadProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe tallentaessa ParrotData.xml tiedostoa: {0}.
        /// </summary>
        public static string ErrorCantSaveParrotData {
            get {
                return ResourceManager.GetString("ErrorCantSaveParrotData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelin käynnistystiedostoa ei ole asetettu! Aseta se Peli Asetuksista..
        /// </summary>
        public static string ErrorGamePathNotSet {
            get {
                return ResourceManager.GetString("ErrorGamePathNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keskuspalvelin ei vastaa..
        /// </summary>
        public static string ErrorMasterServerOffline {
            get {
                return ResourceManager.GetString("ErrorMasterServerOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näyttää siltä että purit minut erittäin vanhan TeknoParrotin kansioon, ole hyvä ja pura minut uuteen kansioon..
        /// </summary>
        public static string ErrorOldTeknoParrotDirectory {
            get {
                return ResourceManager.GetString("ErrorOldTeknoParrotDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näyttää siltä että käynnistit minut ensimmäistä kertaa, muista asettaa kaikki asetukset ja tallentaa ne..
        /// </summary>
        public static string FirstRun {
            get {
                return ResourceManager.GetString("FirstRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelit:.
        /// </summary>
        public static string GameList {
            get {
                return ResourceManager.GetString("GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peli Käynnissä.
        /// </summary>
        public static string GameRunning {
            get {
                return ResourceManager.GetString("GameRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koska suljit emulaattorin väkisin, suosittelen että tarkistat tehtävienhallinnasta että mitään prosesseja ei jäänyt päälle..
        /// </summary>
        public static string GameRunningCheckTaskMgr {
            get {
                return ResourceManager.GetString("GameRunningCheckTaskMgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakota Pelin Sulkeminen.
        /// </summary>
        public static string GameRunningForceQuit {
            get {
                return ResourceManager.GetString("GameRunningForceQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peli Pysäytetty.
        /// </summary>
        public static string GameRunningGameStopped {
            get {
                return ResourceManager.GetString("GameRunningGameStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelin käynnistystiedosto:.
        /// </summary>
        public static string GameSettingsGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelin käynnistystiedosto.
        /// </summary>
        public static string GameSettingsGameExecutableFilter {
            get {
                return ResourceManager.GetString("GameSettingsGameExecutableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse pelin käynnistys tiedosto.
        /// </summary>
        public static string GameSettingsSelectGameExecutable {
            get {
                return ResourceManager.GetString("GameSettingsSelectGameExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoja.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pahoittelut. Tämä peli vaatii 64 bittisen käyttöjärjestelmän, sinulla näyttää olevan vain 32 bittinen..
        /// </summary>
        public static string Library64bit {
            get {
                return ResourceManager.GetString("Library64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinulla näyttää olevan jo toinen emulaattori käytössä..
        /// </summary>
        public static string LibraryAnotherEmulator {
            get {
                return ResourceManager.GetString("LibraryAnotherEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ole hyvä ja päivitä OpenParrot! Näyttää siltä että tämä ei ole virallinen {0} tiedosto! Peli saattaa kaatua tai olla epävakaa. Haluatko jatkaa?.
        /// </summary>
        public static string LibraryBadiDMAC {
            get {
                return ResourceManager.GetString("LibraryBadiDMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En löydä käynnistystiedostoa: {0}.
        /// </summary>
        public static string LibraryCantFindGame {
            get {
                return ResourceManager.GetString("LibraryCantFindGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En löydä kirjastotiedostoa {0}!Pura TeknoParrot uudestaan..
        /// </summary>
        public static string LibraryCantFindLoader {
            get {
                return ResourceManager.GetString("LibraryCantFindLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OHJAIN ASETUKSET.
        /// </summary>
        public static string LibraryControllerSetup {
            get {
                return ResourceManager.GetString("LibraryControllerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tämä lataa kaikki esikatselukuvat peleille, oletko varma että haluat ladata ne? Ladattava tiedosto on noin 50 megaa..
        /// </summary>
        public static string LibraryDownloadAllIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadAllIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATAA PUUTTUVAT ESIKATSELUKUVAT.
        /// </summary>
        public static string LibraryDownloadMissingIcons {
            get {
                return ResourceManager.GetString("LibraryDownloadMissingIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulaattori.
        /// </summary>
        public static string LibraryEmulator {
            get {
                return ResourceManager.GetString("LibraryEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelin sijaintia ei ole asetettu, ole hyvä ja aseta se peli asetuksista..
        /// </summary>
        public static string LibraryGameLocationNotSet {
            get {
                return ResourceManager.GetString("LibraryGameLocationNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PELI ASETUKSET.
        /// </summary>
        public static string LibraryGameSettings {
            get {
                return ResourceManager.GetString("LibraryGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelisi kansiossa on mahdollisesti viallisia tiedostoa. Seuraavanlaiset tiedostot tulisi poistaa kansiosta ennen pelin pelaamista: .
        /// </summary>
        public static string LibraryInvalidFiles {
            get {
                return ResourceManager.GetString("LibraryInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paina kyllä jos haluat käynnistää pelin joka tapauksessa..
        /// </summary>
        public static string LibraryInvalidFilesContinue {
            get {
                return ResourceManager.GetString("LibraryInvalidFilesContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KÄYNNISTÄ PELI.
        /// </summary>
        public static string LibraryLaunchGame {
            get {
                return ResourceManager.GetString("LibraryLaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LISÄTIETOJA.
        /// </summary>
        public static string LibraryMoreInfo {
            get {
                return ResourceManager.GetString("LibraryMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näyttää siltä ettei minulla ole Administrator oikeuksia. Peli {0] vaatii että minulla on nämä oikeudet tai se ei toimi oikein. Haluatko jatkaa silti?.
        /// </summary>
        public static string LibraryNeedsAdmin {
            get {
                return ResourceManager.GetString("LibraryNeedsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Et ole lisännyt vielä yhtään peliä, haluatko lisätä niitä nyt?.
        /// </summary>
        public static string LibraryNoGames {
            get {
                return ResourceManager.GetString("LibraryNoGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koitat tarkistaa pelin eheyttä mutta pelillä ei ole vielä eheystiedostoa..
        /// </summary>
        public static string LibraryNoHashes {
            get {
                return ResourceManager.GetString("LibraryNoHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelistä ei ole lisätietoja saatavilla..
        /// </summary>
        public static string LibraryNoInfo {
            get {
                return ResourceManager.GetString("LibraryNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testiruutu.
        /// </summary>
        public static string LibraryTestMenu {
            get {
                return ResourceManager.GetString("LibraryTestMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käynnistä testiruutuun..
        /// </summary>
        public static string LibraryToggleTestMode {
            get {
                return ResourceManager.GetString("LibraryToggleTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARKISTA PELIN EHEYS.
        /// </summary>
        public static string LibraryVerifyGame {
            get {
                return ResourceManager.GetString("LibraryVerifyGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoja.
        /// </summary>
        public static string MainAbout {
            get {
                return ResourceManager.GetString("MainAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oletko varma?.
        /// </summary>
        public static string MainAreYouSure {
            get {
                return ResourceManager.GetString("MainAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjasto.
        /// </summary>
        public static string MainLibrary {
            get {
                return ResourceManager.GetString("MainLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopeta ohjelma.
        /// </summary>
        public static string MainQuit {
            get {
                return ResourceManager.GetString("MainQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asetukset.
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeknoParrot Online.
        /// </summary>
        public static string MainTPOnline {
            get {
                return ResourceManager.GetString("MainTPOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auta projektia pienellä summalla ja saa uskomattomia patreon etuja!.
        /// </summary>
        public static string PatreonBecomeAPatron {
            get {
                return ResourceManager.GetString("PatreonBecomeAPatron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktivoi Patreon avain.
        /// </summary>
        public static string PatreonDeregisterKey {
            get {
                return ResourceManager.GetString("PatreonDeregisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe toisesta prosessista:.
        /// </summary>
        public static string PatreonError {
            get {
                return ResourceManager.GetString("PatreonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon avain ei kyllä näytä tältä..
        /// </summary>
        public static string PatreonMustNotBeBlank {
            get {
                return ResourceManager.GetString("PatreonMustNotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekisteröi Patreon avain.
        /// </summary>
        public static string PatreonRegisterKey {
            get {
                return ResourceManager.GetString("PatreonRegisterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tila:.
        /// </summary>
        public static string PatreonStatus {
            get {
                return ResourceManager.GetString("PatreonStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkista päivitykset käynnistäessä..
        /// </summary>
        public static string SettingsCheckForUpdates {
            get {
                return ResourceManager.GetString("SettingsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näytä &quot;oletko varma&quot; dialogi suljettaessa..
        /// </summary>
        public static string SettingsConfirmExit {
            get {
                return ResourceManager.GetString("SettingsConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Input Ratti Asetukset.
        /// </summary>
        public static string SettingsDInputWheel {
            get {
                return ResourceManager.GetString("SettingsDInputWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataa Force Feedback lisäosa (Ohjain/Ratti tärinät).
        /// </summary>
        public static string SettingsDownloadFFB {
            get {
                return ResourceManager.GetString("SettingsDownloadFFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lataa pelin esikatselukuva kun valitset pelin listasta..
        /// </summary>
        public static string SettingsDownloadIcon {
            get {
                return ResourceManager.GetString("SettingsDownloadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Axis Brake.
        /// </summary>
        public static string SettingsFullBrake {
            get {
                return ResourceManager.GetString("SettingsFullBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Axis Gas.
        /// </summary>
        public static string SettingsFullGas {
            get {
                return ResourceManager.GetString("SettingsFullGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttöliittymän rautakiihdytys pois päältä.
        /// </summary>
        public static string SettingsHardwareAccel {
            get {
                return ResourceManager.GetString("SettingsHardwareAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piilota konsoli ikkunat.
        /// </summary>
        public static string SettingsHideConsoleWindows {
            get {
                return ResourceManager.GetString("SettingsHideConsoleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aseen ohjain asetukset.
        /// </summary>
        public static string SettingsJoystickGunSettings {
            get {
                return ResourceManager.GetString("SettingsJoystickGunSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muista edellinen peli uudelleen käynnistäessä..
        /// </summary>
        public static string SettingsLoadLastPlayed {
            get {
                return ResourceManager.GetString("SettingsLoadLastPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1 Aseen Herkkyys Ohjaimella.
        /// </summary>
        public static string SettingsP1GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP1GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2 Aseen Herkkyys Ohjaimella.
        /// </summary>
        public static string SettingsP2GunJoystickSensitivity {
            get {
                return ResourceManager.GetString("SettingsP2GunJoystickSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Axis Brake.
        /// </summary>
        public static string SettingsReverseBrake {
            get {
                return ResourceManager.GetString("SettingsReverseBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Axis Gas.
        /// </summary>
        public static string SettingsReverseGas {
            get {
                return ResourceManager.GetString("SettingsReverseGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallenna asetukset.
        /// </summary>
        public static string SettingsSaveSettings {
            get {
                return ResourceManager.GetString("SettingsSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näytä discordissa että pelaat TeknoParrotilla..
        /// </summary>
        public static string SettingsShowGameOnDiscord {
            get {
                return ResourceManager.GetString("SettingsShowGameOnDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kytke päälle sto0z alue..
        /// </summary>
        public static string SettingsSto0zZone {
            get {
                return ResourceManager.GetString("SettingsSto0zZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väri.
        /// </summary>
        public static string SettingsUIColour {
            get {
                return ResourceManager.GetString("SettingsUIColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulkoasun Muokkaus (Patreon Tukijoille).
        /// </summary>
        public static string SettingsUICustomization {
            get {
                return ResourceManager.GetString("SettingsUICustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pimeä tila.
        /// </summary>
        public static string SettingsUIDarkMode {
            get {
                return ResourceManager.GetString("SettingsUIDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ota automaattisesti käyttöön lomakausien ulkoasuteemat..
        /// </summary>
        public static string SettingsUIHolidayThemes {
            get {
                return ResourceManager.GetString("SettingsUIHolidayThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onnistuneesti tallennettu {0}!.
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luo Aula Ja Käynnistä Peli.
        /// </summary>
        public static string TPOCreateLobby {
            get {
                return ResourceManager.GetString("TPOCreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suodata peli:.
        /// </summary>
        public static string TPOFilter {
            get {
                return ResourceManager.GetString("TPOFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peli.
        /// </summary>
        public static string TPOGame {
            get {
                return ResourceManager.GetString("TPOGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liity Aulaan Ja Käynnistä Peli.
        /// </summary>
        public static string TPOJoinLobby {
            get {
                return ResourceManager.GetString("TPOJoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aulan nimi.
        /// </summary>
        public static string TPOLobbyName {
            get {
                return ResourceManager.GetString("TPOLobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelaajat.
        /// </summary>
        public static string TPOPlayers {
            get {
                return ResourceManager.GetString("TPOPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päivitä aulat.
        /// </summary>
        public static string TPORefresh {
            get {
                return ResourceManager.GetString("TPORefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi päivitys on ladattavissa..
        /// </summary>
        public static string UpdaterAvailable {
            get {
                return ResourceManager.GetString("UpdaterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei Asennettu.
        /// </summary>
        public static string UpdaterNotInstalled {
            get {
                return ResourceManager.GetString("UpdaterNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näytä muutokset.
        /// </summary>
        public static string UpdaterOpenChangelog {
            get {
                return ResourceManager.GetString("UpdaterOpenChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käynnistetäänkö TeknoParrotUi uudestaan päivityksen jälkeen? Muussa tapauksessa se suljetaan..
        /// </summary>
        public static string UpdaterRestart {
            get {
                return ResourceManager.GetString("UpdaterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onnistuneesti päivitettiin {0} versioon {1}.
        /// </summary>
        public static string UpdaterSuccess {
            get {
                return ResourceManager.GetString("UpdaterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Päivitä.
        /// </summary>
        public static string UpdaterUpdate {
            get {
                return ResourceManager.GetString("UpdaterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eheyden Tarkastaminen Peruutettu..
        /// </summary>
        public static string VerifyCancelled {
            get {
                return ResourceManager.GetString("VerifyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarkistetaan Pelin Eheyttä....
        /// </summary>
        public static string VerifyChecking {
            get {
                return ResourceManager.GetString("VerifyChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poikkeavat pelitiedostot.
        /// </summary>
        public static string VerifyFilesInvalid {
            get {
                return ResourceManager.GetString("VerifyFilesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your game appears to have invalid files. This could be due to a bad download, bad dump, virus infection, or you have modifications installed like resolution and english patches..
        /// </summary>
        public static string VerifyFilesInvalidExplain {
            get {
                return ResourceManager.GetString("VerifyFilesInvalidExplain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eheät pelitiedostot.
        /// </summary>
        public static string VerifyFilesValid {
            get {
                return ResourceManager.GetString("VerifyFilesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poikkeava:.
        /// </summary>
        public static string VerifyInvalid {
            get {
                return ResourceManager.GetString("VerifyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eheä:.
        /// </summary>
        public static string VerifyValid {
            get {
                return ResourceManager.GetString("VerifyValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varoitus.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyllä.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
