<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../TeknoParrotUi.Common/TeknoParrotUi.Common.csproj" />
  </ItemGroup>
</Project>
